// Mirrors backend/src/config/events.ts — keep in sync.
export const EVENTS = {
  SESSION: 'session',
  ROOM_REJOINED: 'room_rejoined',
  LEAVE_ROOM: 'leave_room',
  LIST_ROOMS: 'list_rooms',
  REQUEST_STATE: 'request_state',
  CREATE_ROOM: 'create_room',
  JOIN_ROOM: 'join_room',
  JOIN_RANDOM_ROOM: 'room:join_random',
  ROOM_ERROR: 'room:error',
  UPDATE_SETTINGS: 'update_settings',
  ROOM_UPDATED: 'room_updated',
  START_GAME: 'start_game',
  PLAYER_JOINED: 'player_joined',
  PLAYER_LEFT: 'player_left',
  GAME_STATE: 'game_state',
  ROUND_START: 'round_start',
  WORD_CHOSEN: 'word_chosen',
  HINT_UPDATE: 'hint_update',
  PLAYERS_UPDATE: 'players_update',
  ROUND_END: 'round_end',
  GAME_OVER: 'game_over',
  DRAW_START: 'draw_start',
  DRAW_MOVE: 'draw_move',
  DRAW_END: 'draw_end',
  DRAW_FILL: 'draw_fill',
  DRAW_DATA: 'draw_data',
  CANVAS_CLEAR: 'canvas_clear',
  DRAW_UNDO: 'draw_undo',
  GUESS: 'guess',
  GUESS_RESULT: 'guess_result',
  CHAT: 'chat',
  CHAT_MESSAGE: 'chat_message',
} as const;
